version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: conexa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
