version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=Host=db;Port=5432;Database=challenge;Username=admin;Password=conexa
    ports:
      - "8080:80"
    volumes: []
